export const quizzes = [
    {
        id: "1",
        title: "General Knowledge",
        description: "Challenge yourself with a wide range of trivia questions.",
        questions: [
            { text: "What is the capital of France?", options: ["Paris", "London", "Berlin", "Madrid"], correct: "Paris" },
            { text: "Which country is known as the Land of the Rising Sun?", options: ["Japan", "China", "Thailand", "India"], correct: "Japan" },
            { text: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correct: "Pacific" },
            { text: "Which planet is known as the Blue Planet?", options: ["Earth", "Neptune", "Uranus", "Mars"], correct: "Earth" },
            { text: "What is the hardest natural substance?", options: ["Diamond", "Graphite", "Steel", "Gold"], correct: "Diamond" },
            { text: "How many continents are there?", options: ["6", "7", "5", "8"], correct: "7" },
            { text: "Which element has the chemical symbol O?", options: ["Oxygen", "Gold", "Osmium", "Ozone"], correct: "Oxygen" },
            { text: "What year did World War I begin?", options: ["1914", "1918", "1939", "1945"], correct: "1914" },
            { text: "Who painted the Mona Lisa?", options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Van Gogh"], correct: "Leonardo da Vinci" },
            { text: "What is the capital of Australia?", options: ["Canberra", "Sydney", "Melbourne", "Perth"], correct: "Canberra" },
            { text: "Which country has the most FIFA World Cup wins?", options: ["Brazil", "Germany", "Italy", "Argentina"], correct: "Brazil" },
            { text: "What is the smallest country in the world?", options: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], correct: "Vatican City" },
            { text: "What is the chemical formula for water?", options: ["H2O", "O2", "CO2", "NaCl"], correct: "H2O" },
            { text: "Which language is most spoken worldwide?", options: ["Mandarin Chinese", "English", "Hindi", "Spanish"], correct: "Mandarin Chinese" },
            { text: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: "Nile" },
            { text: "What is the square root of 64?", options: ["6", "8", "10", "12"], correct: "8" },
            { text: "Who wrote 'Romeo and Juliet'?", options: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], correct: "William Shakespeare" },
            { text: "What is the largest mammal on Earth?", options: ["Blue Whale", "Elephant", "Humpback Whale", "Giraffe"], correct: "Blue Whale" },
            { text: "How many colors are there in a rainbow?", options: ["6", "7", "8", "9"], correct: "7" },
            { text: "Who is known as the Father of Computers?", options: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"], correct: "Charles Babbage" },
        ],
    },
    {
        id: "2",
        title: "Science & Technology",
        description: "Explore fascinating facts about science and technology.",
        questions: [
            { text: "What planet is known as the Red Planet?", options: ["Mars", "Venus", "Jupiter", "Saturn"], correct: "Mars" },
            { text: "What gas do plants absorb from the atmosphere?", options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"], correct: "Carbon Dioxide" },
            { text: "Who developed the theory of relativity?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Marie Curie"], correct: "Albert Einstein" },
            { text: "What is the chemical symbol for gold?", options: ["Au", "Ag", "Pb", "Fe"], correct: "Au" },
            { text: "What is the boiling point of water in Celsius?", options: ["100°C", "212°C", "32°C", "0°C"], correct: "100°C" },
            { text: "Which organ in the human body is responsible for filtering blood?", options: ["Kidney", "Liver", "Heart", "Lungs"], correct: "Kidney" },
            { text: "What is the speed of light?", options: ["299,792 km/s", "300,000 km/s", "280,000 km/s", "250,000 km/s"], correct: "299,792 km/s" },
            { text: "What is the unit of electrical resistance?", options: ["Ohm", "Watt", "Ampere", "Volt"], correct: "Ohm" },
            { text: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Deoxyribosomal Acid", "Dynamic Nucleic Acid", "Dual Nucleotide Array"], correct: "Deoxyribonucleic Acid" },
            { text: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Mars", "Neptune"], correct: "Saturn" },
            { text: "What is the smallest unit of life?", options: ["Cell", "Atom", "Molecule", "Organ"], correct: "Cell" },
            { text: "Who invented the telephone?", options: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Benjamin Franklin"], correct: "Alexander Graham Bell" },
            { text: "What is the powerhouse of the cell?", options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi Apparatus"], correct: "Mitochondria" },
            { text: "Which part of the brain controls balance?", options: ["Cerebellum", "Cerebrum", "Medulla", "Pons"], correct: "Cerebellum" },
            { text: "What is the first element on the periodic table?", options: ["Hydrogen", "Helium", "Lithium", "Carbon"], correct: "Hydrogen" },
            { text: "Which planet is closest to the Sun?", options: ["Mercury", "Venus", "Earth", "Mars"], correct: "Mercury" },
            { text: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "HyperText Transmission Protocol", "High-Transfer Text Protocol", "HyperTransport Protocol"], correct: "HyperText Transfer Protocol" },
            { text: "What is the symbol for Iron on the periodic table?", options: ["Fe", "Ir", "In", "I"], correct: "Fe" },
            { text: "What is the main component of the Sun?", options: ["Hydrogen", "Helium", "Carbon", "Nitrogen"], correct: "Hydrogen" },
            { text: "What is the SI unit of force?", options: ["Newton", "Joule", "Pascal", "Watt"], correct: "Newton" },
        ],
    },
    {
        id: "3",
        title: "History",
        description: "Test your knowledge of significant historical events.",
        questions: [
            { text: "Who was the first President of the United States?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], correct: "George Washington" },
            { text: "What year did World War II end?", options: ["1945", "1940", "1939", "1950"], correct: "1945" },
            { text: "Which ancient civilization built the pyramids?", options: ["Egyptians", "Romans", "Greeks", "Mayans"], correct: "Egyptians" },
            { text: "Who was the first man to step on the moon?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], correct: "Neil Armstrong" },
            { text: "What empire was ruled by Julius Caesar?", options: ["Roman Empire", "Greek Empire", "Ottoman Empire", "Byzantine Empire"], correct: "Roman Empire" },
            { text: "Which year did the Titanic sink?", options: ["1912", "1905", "1920", "1931"], correct: "1912" },
            { text: "Who was the first female Prime Minister of the United Kingdom?", options: ["Margaret Thatcher", "Theresa May", "Queen Victoria", "Angela Merkel"], correct: "Margaret Thatcher" },
            { text: "Who discovered America in 1492?", options: ["Christopher Columbus", "Vasco da Gama", "Marco Polo", "Ferdinand Magellan"], correct: "Christopher Columbus" },
            { text: "Which wall fell in 1989, symbolizing the end of the Cold War?", options: ["Berlin Wall", "Great Wall of China", "Iron Curtain", "Western Wall"], correct: "Berlin Wall" },
            { text: "What was the name of the ship on which the Pilgrims traveled to America?", options: ["Mayflower", "Santa Maria", "Pinta", "Victoria"], correct: "Mayflower" },
            { text: "Who was the first Emperor of Rome?", options: ["Augustus", "Julius Caesar", "Nero", "Caligula"], correct: "Augustus" },
            { text: "What was the name of the trade route connecting China and Europe?", options: ["Silk Road", "Spice Route", "Amber Road", "Gold Road"], correct: "Silk Road" },
            { text: "Who wrote the Communist Manifesto?", options: ["Karl Marx", "Friedrich Engels", "Vladimir Lenin", "Joseph Stalin"], correct: "Karl Marx" },
            { text: "In which year was the Declaration of Independence signed?", options: ["1776", "1775", "1781", "1789"], correct: "1776" },
            { text: "Who was the first woman to win a Nobel Prize?", options: ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Florence Nightingale"], correct: "Marie Curie" },
            { text: "What was the name of the ancient Greek war between Athens and Sparta?", options: ["Peloponnesian War", "Trojan War", "Persian Wars", "Macedonian Wars"], correct: "Peloponnesian War" },
            { text: "Who was known as the Maid of Orléans?", options: ["Joan of Arc", "Catherine the Great", "Marie Antoinette", "Elizabeth I"], correct: "Joan of Arc" },
            { text: "Which US president abolished slavery?", options: ["Abraham Lincoln", "George Washington", "Theodore Roosevelt", "Ulysses S. Grant"], correct: "Abraham Lincoln" },
            { text: "What was the name of the first artificial Earth satellite launched by the Soviet Union?", options: ["Sputnik 1", "Luna 1", "Explorer 1", "Vostok 1"], correct: "Sputnik 1" },
            { text: "Who was the leader of the Indian independence movement against British rule?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel"], correct: "Mahatma Gandhi" },
        ],
    },
    {
        id: "4",
        title: "Sports",
        description: "Prove your expertise in sports trivia.",
        questions: [
            { text: "How many players are on a soccer team?", options: ["11", "10", "9", "12"], correct: "11" },
            { text: "What is the length of an Olympic swimming pool?", options: ["50 meters", "25 meters", "100 meters", "75 meters"], correct: "50 meters" },
            { text: "Who has won the most Grand Slam titles in tennis?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Serena Williams"], correct: "Novak Djokovic" },
            { text: "What is the term for a score of zero in tennis?", options: ["Love", "Duck", "Blank", "Void"], correct: "Love" },
            { text: "Which country hosted the 2016 Summer Olympics?", options: ["Brazil", "China", "Japan", "Russia"], correct: "Brazil" },
            { text: "Which sport is known as 'the gentleman's game'?", options: ["Cricket", "Golf", "Tennis", "Baseball"], correct: "Cricket" },
            { text: "How many points is a touchdown worth in American football?", options: ["6", "7", "3", "4"], correct: "6" },
            { text: "What is the maximum score in a single frame of bowling?", options: ["300", "200", "150", "250"], correct: "300" },
            { text: "Which country has won the most Cricket World Cups?", options: ["Australia", "India", "England", "West Indies"], correct: "Australia" },
            { text: "Who holds the record for the fastest 100-meter sprint?", options: ["Usain Bolt", "Carl Lewis", "Tyson Gay", "Asafa Powell"], correct: "Usain Bolt" },
            { text: "Which sport uses the terms 'birdie' and 'eagle'?", options: ["Golf", "Badminton", "Tennis", "Soccer"], correct: "Golf" },
            { text: "How many rings are there on the Olympic flag?", options: ["5", "4", "6", "7"], correct: "5" },
            { text: "Which country has won the most NBA championships?", options: ["USA", "Canada", "Spain", "Argentina"], correct: "USA" },
            { text: "What does MLB stand for?", options: ["Major League Baseball", "Major League Basketball", "Master League Baseball", "Master League Basketball"], correct: "Major League Baseball" },
            { text: "Which team won the first FIFA World Cup?", options: ["Uruguay", "Brazil", "Germany", "Italy"], correct: "Uruguay" },
            { text: "What is the national sport of Japan?", options: ["Sumo Wrestling", "Baseball", "Judo", "Karate"], correct: "Sumo Wrestling" },
            { text: "What is the standard height of a basketball hoop?", options: ["10 feet", "12 feet", "8 feet", "9 feet"], correct: "10 feet" },
            { text: "Who is known as the 'King of Soccer'?", options: ["Pelé", "Maradona", "Messi", "Cristiano Ronaldo"], correct: "Pelé" },
            { text: "How many holes are there in a standard golf course?", options: ["18", "9", "12", "15"], correct: "18" },
            { text: "Which sport is known as the fastest game on ice?", options: ["Ice Hockey", "Figure Skating", "Speed Skating", "Curling"], correct: "Ice Hockey" },
        ],
    },
    {
        id: "5",
        title: "Movies & Entertainment",
        description: "Show off your movie and entertainment knowledge.",
        questions: [
            { text: "Who directed the movie 'Inception'?", options: ["Christopher Nolan", "Steven Spielberg", "James Cameron", "Quentin Tarantino"], correct: "Christopher Nolan" },
            { text: "What is the name of Harry Potter's pet owl?", options: ["Hedwig", "Errol", "Pigwidgeon", "Crookshanks"], correct: "Hedwig" },
            { text: "Which movie features the song 'My Heart Will Go On'?", options: ["Titanic", "The Bodyguard", "Frozen", "Moulin Rouge"], correct: "Titanic" },
            { text: "Who played the Joker in 'The Dark Knight'?", options: ["Heath Ledger", "Joaquin Phoenix", "Jack Nicholson", "Jared Leto"], correct: "Heath Ledger" },
            { text: "What year was the first Star Wars movie released?", options: ["1977", "1980", "1975", "1983"], correct: "1977" },
            { text: "Which animated movie is about a clownfish searching for his son?", options: ["Finding Nemo", "Shark Tale", "The Little Mermaid", "Moana"], correct: "Finding Nemo" },
            { text: "What is the highest-grossing movie of all time?", options: ["Avatar", "Avengers: Endgame", "Titanic", "The Lion King"], correct: "Avatar" },
            { text: "Who directed 'Pulp Fiction'?", options: ["Quentin Tarantino", "Martin Scorsese", "Ridley Scott", "James Cameron"], correct: "Quentin Tarantino" },
            { text: "What is the name of the hobbit played by Elijah Wood in 'The Lord of the Rings'?", options: ["Frodo Baggins", "Samwise Gamgee", "Bilbo Baggins", "Peregrin Took"], correct: "Frodo Baggins" },
            { text: "Which Disney movie features the song 'Let It Go'?", options: ["Frozen", "Tangled", "Moana", "Brave"], correct: "Frozen" },
            { text: "Which actor played Forrest Gump?", options: ["Tom Hanks", "Brad Pitt", "Leonardo DiCaprio", "Matt Damon"], correct: "Tom Hanks" },
            { text: "What is the name of the kingdom in the movie 'Frozen'?", options: ["Arendelle", "Corona", "Atlantica", "Narnia"], correct: "Arendelle" },
            { text: "Who directed the movie 'Jaws'?", options: ["Steven Spielberg", "Martin Scorsese", "Ridley Scott", "George Lucas"], correct: "Steven Spielberg" },
            { text: "What is the name of Simba's father in 'The Lion King'?", options: ["Mufasa", "Scar", "Zazu", "Rafiki"], correct: "Mufasa" },
            { text: "Who played Iron Man in the Marvel Cinematic Universe?", options: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"], correct: "Robert Downey Jr." },
            { text: "What is the name of the princess in 'Sleeping Beauty'?", options: ["Aurora", "Belle", "Cinderella", "Rapunzel"], correct: "Aurora" },
            { text: "Which movie franchise features a character named Jack Sparrow?", options: ["Pirates of the Caribbean", "Indiana Jones", "Star Wars", "The Mummy"], correct: "Pirates of the Caribbean" },
            { text: "Who directed the movie 'The Godfather'?", options: ["Francis Ford Coppola", "Martin Scorsese", "Quentin Tarantino", "Steven Spielberg"], correct: "Francis Ford Coppola" },
            { text: "What is the name of the robot in 'Wall-E'?", options: ["Wall-E", "Eve", "R2-D2", "C-3PO"], correct: "Wall-E" },
            { text: "Which actor starred in 'Mission: Impossible' as Ethan Hunt?", options: ["Tom Cruise", "Matt Damon", "Brad Pitt", "Keanu Reeves"], correct: "Tom Cruise" },
        ],
    },

];
